## Color Scheme

background_opacity 0.9
font_family JetBrains Mono
font_size 14
bold_font JetBrains Mono Bold
bold_italic_font JetBrains Mono Bold Italic

# hide macbar
hide_window_decorations titlebar-only


# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
